/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Healthz */
    get: operations["healthz_healthz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Index
     * @description The search page. ``?q=`` prefills the box so result pages are linkable.
     */
    get: operations["index__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Api Search */
    get: operations["api_search_api_search_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/cover/{source}/{item_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Api Cover
     * @description Proxy cover images so backend credentials never reach the browser.
     */
    get: operations["api_cover_api_cover__source___item_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * BookResult
     * @description A single book, however it was found.
     */
    BookResult: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Subtitle */
      subtitle?: string | null;
      /** Authors */
      authors?: string[];
      /** Series */
      series?: string | null;
      /** Series Index */
      series_index?: string | null;
      /** Year */
      year?: string | null;
      /** Formats */
      formats?: string[];
      /** Narrators */
      narrators?: string[];
      /** Identifiers */
      identifiers?: {
        [key: string]: string;
      };
      /** Cover Url */
      cover_url?: string | null;
      /** Item Url */
      item_url?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** SearchResponse */
    SearchResponse: {
      /** Query */
      query: string;
      /** Shelfmark Url */
      shelfmark_url?: string | null;
      /** Sources */
      sources?: components["schemas"]["SourceResult"][];
    };
    /**
     * SourceResult
     * @description Per-source outcome. A failure here is data, not an HTTP error.
     */
    SourceResult: {
      /** Key */
      key: string;
      /** Label */
      label: string;
      status: components["schemas"]["SourceStatus"];
      /** Error */
      error?: string | null;
      /** Results */
      results?: components["schemas"]["BookResult"][];
      /** Count */
      readonly count: number;
    };
    /**
     * SourceStatus
     * @enum {string}
     */
    SourceStatus: "ok" | "error" | "disabled";
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  healthz_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  index__get: {
    parameters: {
      query?: {
        q?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  api_search_api_search_get: {
    parameters: {
      query?: {
        q?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SearchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  api_cover_api_cover__source___item_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        source: string;
        item_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
